version: '2'
services:
    jhipdemo-elasticsearch:
        container_name: jhipdemo-elasticsearch
        image: elasticsearch:2.4.1
        # volumes:
        #     - ~/volumes/jhipster/jhipdemo/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
